# Create improved streamlit_app.py - With working bar charts and graphs
import os

# Delete old file
if os.path.exists('streamlit_app.py'):
    os.remove('streamlit_app.py')

# Create file line by line
with open('streamlit_app.py', 'w', encoding='utf-8') as f:
    f.write("import streamlit as st\n")
    f.write("import pandas as pd\n")
    f.write("import numpy as np\n")
    f.write("import matplotlib.pyplot as plt\n")
    f.write("import seaborn as sns\n")
    f.write("from sklearn.preprocessing import StandardScaler, LabelEncoder\n")
    f.write("from sklearn.cluster import KMeans, DBSCAN\n")
    f.write("from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score\n")
    f.write("from sklearn.decomposition import PCA\n")
    f.write("\n")
    f.write("st.set_page_config(page_title='Customer Segmentation', layout='wide')\n")
    f.write("st.title('Customer Segmentation Dashboard')\n")
    f.write("\n")
    f.write("st.sidebar.header('Upload & Settings')\n")
    f.write("uploaded_file = st.sidebar.file_uploader('Upload CSV Dataset', type=['csv'])\n")
    f.write("\n")
    f.write("# Create dropdown menu in sidebar\n")
    f.write("st.sidebar.subheader('Navigation')\n")
    f.write("page = st.sidebar.selectbox(\n")
    f.write("    'Choose Analysis Type',\n")
    f.write("    ['K-Means Clustering', 'DBSCAN Clustering', 'Method Comparison', 'Customer Profiling']\n")
    f.write(")\n")
    f.write("\n")
    f.write("if uploaded_file:\n")
    f.write("    # Load data\n")
    f.write("    df = pd.read_csv(uploaded_file)\n")
    f.write("    st.subheader('Dataset Preview')\n")
    f.write("    st.dataframe(df.head())\n")
    f.write("    \n")
    f.write("    # Preprocessing\n")
    f.write("    df_clean = df.copy()\n")
    f.write("    \n")
    f.write("    # Handle column names\n")
    f.write("    if 'Annual Income (k$)' in df_clean.columns:\n")
    f.write("        df_clean.rename(columns={'Annual Income (k$)': 'Annual_Income'}, inplace=True)\n")
    f.write("    if 'Spending Score (1-100)' in df_clean.columns:\n")
    f.write("        df_clean.rename(columns={'Spending Score (1-100)': 'Spending_Score'}, inplace=True)\n")
    f.write("    \n")
    f.write("    # Encode Gender\n")
    f.write("    if 'Gender' in df_clean.columns:\n")
    f.write("        le = LabelEncoder()\n")
    f.write("        df_clean['Gender_Encoded'] = le.fit_transform(df_clean['Gender'])\n")
    f.write("    else:\n")
    f.write("        df_clean['Gender_Encoded'] = 0\n")
    f.write("    \n")
    f.write("    # Features\n")
    f.write("    features = ['Age', 'Annual_Income', 'Spending_Score', 'Gender_Encoded']\n")
    f.write("    X = df_clean[features].copy()\n")
    f.write("    \n")
    f.write("    # Scale\n")
    f.write("    scaler = StandardScaler()\n")
    f.write("    X_scaled = scaler.fit_transform(X)\n")
    f.write("    \n")
    f.write("    # Initialize session state\n")
    f.write("    if 'kmeans_labels' not in st.session_state:\n")
    f.write("        st.session_state.kmeans_labels = None\n")
    f.write("    if 'kmeans_k' not in st.session_state:\n")
    f.write("        st.session_state.kmeans_k = None\n")
    f.write("    if 'kmeans_sil' not in st.session_state:\n")
    f.write("        st.session_state.kmeans_sil = None\n")
    f.write("    if 'kmeans_cal' not in st.session_state:\n")
    f.write("        st.session_state.kmeans_cal = None\n")
    f.write("    if 'kmeans_dav' not in st.session_state:\n")
    f.write("        st.session_state.kmeans_dav = None\n")
    f.write("    if 'dbscan_labels' not in st.session_state:\n")
    f.write("        st.session_state.dbscan_labels = None\n")
    f.write("    if 'dbscan_clusters' not in st.session_state:\n")
    f.write("        st.session_state.dbscan_clusters = None\n")
    f.write("    if 'dbscan_noise' not in st.session_state:\n")
    f.write("        st.session_state.dbscan_noise = None\n")
    f.write("    if 'dbscan_sil' not in st.session_state:\n")
    f.write("        st.session_state.dbscan_sil = None\n")
    f.write("    if 'kmeans_df' not in st.session_state:\n")
    f.write("        st.session_state.kmeans_df = None\n")
    f.write("    \n")
    f.write("    # ============================================\n")
    f.write("    # K-MEANS CLUSTERING PAGE\n")
    f.write("    # ============================================\n")
    f.write("    if page == 'K-Means Clustering':\n")
    f.write("        st.header('K-Means Clustering')\n")
    f.write("        \n")
    f.write("        col1, col2 = st.columns([1, 2])\n")
    f.write("        \n")
    f.write("        with col1:\n")
    f.write("            k_value = st.slider('Number of Clusters (k)', 2, 10, 5)\n")
    f.write("            if st.button('Run K-Means', type='primary'):\n")
    f.write("                with st.spinner('Running K-Means...'):\n")
    f.write("                    kmeans = KMeans(n_clusters=k_value, random_state=42, n_init=10)\n")
    f.write("                    labels = kmeans.fit_predict(X_scaled)\n")
    f.write("                    df_clean['Cluster'] = labels\n")
    f.write("                    \n")
    f.write("                    sil_score = silhouette_score(X_scaled, labels)\n")
    f.write("                    cal_score = calinski_harabasz_score(X_scaled, labels)\n")
    f.write("                    dav_score = davies_bouldin_score(X_scaled, labels)\n")
    f.write("                    \n")
    f.write("                    st.session_state.kmeans_labels = labels\n")
    f.write("                    st.session_state.kmeans_k = k_value\n")
    f.write("                    st.session_state.kmeans_sil = sil_score\n")
    f.write("                    st.session_state.kmeans_cal = cal_score\n")
    f.write("                    st.session_state.kmeans_dav = dav_score\n")
    f.write("                    st.session_state.kmeans_df = df_clean.copy()\n")
    f.write("                    \n")
    f.write("                    st.success('Done! Silhouette Score: ' + str(round(sil_score, 4)))\n")
    f.write("        \n")
    f.write("        with col2:\n")
    f.write("            if st.session_state.kmeans_labels is not None:\n")
    f.write("                m1, m2, m3 = st.columns(3)\n")
    f.write("                m1.metric('Silhouette Score', str(round(st.session_state.kmeans_sil, 4)))\n")
    f.write("                m2.metric('Calinski-Harabasz', str(round(st.session_state.kmeans_cal, 0)))\n")
    f.write("                m3.metric('Davies-Bouldin', str(round(st.session_state.kmeans_dav, 4)))\n")
    f.write("        \n")
    f.write("        if st.session_state.kmeans_labels is not None:\n")
    f.write("            pca = PCA(n_components=2)\n")
    f.write("            X_pca = pca.fit_transform(X_scaled)\n")
    f.write("            \n")
    f.write("            fig, ax = plt.subplots(figsize=(10, 6))\n")
    f.write("            scatter = ax.scatter(X_pca[:, 0], X_pca[:, 1], c=st.session_state.kmeans_labels, cmap='viridis', s=100, alpha=0.6)\n")
    f.write("            plt.colorbar(scatter)\n")
    f.write("            ax.set_xlabel('First Principal Component')\n")
    f.write("            ax.set_ylabel('Second Principal Component')\n")
    f.write("            ax.set_title('K-Means Clustering Results')\n")
    f.write("            st.pyplot(fig)\n")
    f.write("    \n")
    f.write("    # ============================================\n")
    f.write("    # DBSCAN CLUSTERING PAGE\n")
    f.write("    # ============================================\n")
    f.write("    elif page == 'DBSCAN Clustering':\n")
    f.write("        st.header('DBSCAN Clustering')\n")
    f.write("        \n")
    f.write("        col1, col2 = st.columns([1, 2])\n")
    f.write("        \n")
    f.write("        with col1:\n")
    f.write("            eps_value = st.slider('Epsilon (eps)', 0.1, 2.0, 0.8, 0.05)\n")
    f.write("            min_samples_value = st.slider('Min Samples', 2, 20, 5)\n")
    f.write("            \n")
    f.write("            if st.button('Run DBSCAN', type='primary'):\n")
    f.write("                with st.spinner('Running DBSCAN...'):\n")
    f.write("                    dbscan = DBSCAN(eps=eps_value, min_samples=min_samples_value)\n")
    f.write("                    labels = dbscan.fit_predict(X_scaled)\n")
    f.write("                    \n")
    f.write("                    n_clusters = len(set(labels)) - (1 if -1 in labels else 0)\n")
    f.write("                    n_noise = list(labels).count(-1)\n")
    f.write("                    \n")
    f.write("                    if n_clusters >= 2:\n")
    f.write("                        mask = labels != -1\n")
    f.write("                        sil_score = silhouette_score(X_scaled[mask], labels[mask])\n")
    f.write("                    else:\n")
    f.write("                        sil_score = -1\n")
    f.write("                    \n")
    f.write("                    st.session_state.dbscan_labels = labels\n")
    f.write("                    st.session_state.dbscan_clusters = n_clusters\n")
    f.write("                    st.session_state.dbscan_noise = n_noise\n")
    f.write("                    st.session_state.dbscan_sil = sil_score\n")
    f.write("                    \n")
    f.write("                    if n_clusters >= 2:\n")
    f.write("                        st.success('Done! Found ' + str(n_clusters) + ' clusters')\n")
    f.write("                        st.info('Silhouette Score (excluding noise): ' + str(round(sil_score, 4)))\n")
    f.write("                    else:\n")
    f.write("                        st.warning('Found only ' + str(n_clusters) + ' clusters. Try adjusting parameters.')\n")
    f.write("        \n")
    f.write("        with col2:\n")
    f.write("            if st.session_state.dbscan_labels is not None:\n")
    f.write("                m1, m2, m3 = st.columns(3)\n")
    f.write("                m1.metric('Clusters Found', st.session_state.dbscan_clusters)\n")
    f.write("                m2.metric('Noise Points', st.session_state.dbscan_noise)\n")
    f.write("                if st.session_state.dbscan_sil > 0:\n")
    f.write("                    m3.metric('Silhouette Score', str(round(st.session_state.dbscan_sil, 4)))\n")
    f.write("                else:\n")
    f.write("                    m3.metric('Silhouette Score', 'N/A')\n")
    f.write("        \n")
    f.write("        if st.session_state.dbscan_labels is not None:\n")
    f.write("            pca = PCA(n_components=2)\n")
    f.write("            X_pca = pca.fit_transform(X_scaled)\n")
    f.write("            \n")
    f.write("            fig, ax = plt.subplots(figsize=(10, 6))\n")
    f.write("            unique_labels = set(st.session_state.dbscan_labels)\n")
    f.write("            \n")
    f.write("            for k in unique_labels:\n")
    f.write("                mask = st.session_state.dbscan_labels == k\n")
    f.write("                if k == -1:\n")
    f.write("                    ax.scatter(X_pca[mask, 0], X_pca[mask, 1], c='black', s=50, label='Noise', alpha=0.5)\n")
    f.write("                else:\n")
    f.write("                    ax.scatter(X_pca[mask, 0], X_pca[mask, 1], s=50, alpha=0.6, label='Cluster ' + str(k))\n")
    f.write("            \n")
    f.write("            ax.set_xlabel('First Principal Component')\n")
    f.write("            ax.set_ylabel('Second Principal Component')\n")
    f.write("            ax.set_title('DBSCAN Clustering Results')\n")
    f.write("            ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')\n")
    f.write("            st.pyplot(fig)\n")
    f.write("    \n")
    f.write("    # ============================================\n")
    f.write("    # METHOD COMPARISON PAGE\n")
    f.write("    # ============================================\n")
    f.write("    elif page == 'Method Comparison':\n")
    f.write("        st.header('Algorithm Comparison')\n")
    f.write("        \n")
    f.write("        if st.session_state.kmeans_labels is not None and st.session_state.dbscan_labels is not None:\n")
    f.write("            comparison_data = {\n")
    f.write("                'Algorithm': ['K-Means', 'DBSCAN'],\n")
    f.write("                'Silhouette Score': [str(round(st.session_state.kmeans_sil, 4)), str(round(st.session_state.dbscan_sil, 4)) if st.session_state.dbscan_sil > 0 else 'N/A'],\n")
    f.write("                'Number of Segments': [st.session_state.kmeans_k, st.session_state.dbscan_clusters],\n")
    f.write("                'Noise Points': ['None (0)', str(st.session_state.dbscan_noise) + ' customers']\n")
    f.write("            }\n")
    f.write("            \n")
    f.write("            comparison_df = pd.DataFrame(comparison_data)\n")
    f.write("            st.dataframe(comparison_df, use_container_width=True)\n")
    f.write("            \n")
    f.write("            st.subheader('Visual Comparison')\n")
    f.write("            \n")
    f.write("            pca = PCA(n_components=2)\n")
    f.write("            X_pca = pca.fit_transform(X_scaled)\n")
    f.write("            \n")
    f.write("            fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n")
    f.write("            \n")
    f.write("            axes[0].scatter(X_pca[:, 0], X_pca[:, 1], c=st.session_state.kmeans_labels, cmap='viridis', s=50, alpha=0.6)\n")
    f.write("            axes[0].set_title('K-Means Clustering')\n")
    f.write("            axes[0].set_xlabel('PC1')\n")
    f.write("            axes[0].set_ylabel('PC2')\n")
    f.write("            \n")
    f.write("            unique_labels = set(st.session_state.dbscan_labels)\n")
    f.write("            for k in unique_labels:\n")
    f.write("                mask = st.session_state.dbscan_labels == k\n")
    f.write("                if k == -1:\n")
    f.write("                    axes[1].scatter(X_pca[mask, 0], X_pca[mask, 1], c='black', s=50, label='Noise', alpha=0.5)\n")
    f.write("                else:\n")
    f.write("                    axes[1].scatter(X_pca[mask, 0], X_pca[mask, 1], s=50, alpha=0.6, label='Cluster ' + str(k))\n")
    f.write("            axes[1].set_title('DBSCAN Clustering')\n")
    f.write("            axes[1].set_xlabel('PC1')\n")
    f.write("            axes[1].set_ylabel('PC2')\n")
    f.write("            axes[1].legend(bbox_to_anchor=(1.05, 1), loc='upper left')\n")
    f.write("            \n")
    f.write("            plt.tight_layout()\n")
    f.write("            st.pyplot(fig)\n")
    f.write("        else:\n")
    f.write("            st.warning('Please run both K-Means and DBSCAN first')\n")
    f.write("    \n")
    f.write("    # ============================================\n")
    f.write("    # CUSTOMER PROFILING PAGE (with graphs)\n")
    f.write("    # ============================================\n")
    f.write("    elif page == 'Customer Profiling':\n")
    f.write("        st.header('Customer Segment Profiles')\n")
    f.write("        \n")
    f.write("        if st.session_state.kmeans_df is not None:\n")
    f.write("            # Display segment table\n")
    f.write("            st.subheader('Segment Overview')\n")
    f.write("            \n")
    f.write("            segment_details = []\n")
    f.write("            \n")
    f.write("            for cluster in range(st.session_state.kmeans_k):\n")
    f.write("                cluster_data = st.session_state.kmeans_df[st.session_state.kmeans_df['Cluster'] == cluster]\n")
    f.write("                \n")
    f.write("                size = len(cluster_data)\n")
    f.write("                percentage = (size / len(st.session_state.kmeans_df)) * 100\n")
    f.write("                age_mean = cluster_data['Age'].mean()\n")
    f.write("                income_mean = cluster_data['Annual_Income'].mean()\n")
    f.write("                spending_mean = cluster_data['Spending_Score'].mean()\n")
    f.write("                \n")
    f.write("                if 'Gender' in cluster_data.columns:\n")
    f.write("                    female_pct = (cluster_data['Gender'] == 'Female').sum() / size * 100\n")
    f.write("                    male_pct = 100 - female_pct\n")
    f.write("                else:\n")
    f.write("                    female_pct, male_pct = 50, 50\n")
    f.write("                \n")
    f.write("                if income_mean > 70 and spending_mean > 60:\n")
    f.write("                    segment_name = 'VIP Premium Customers'\n")
    f.write("                elif income_mean > 70 and spending_mean < 40:\n")
    f.write("                    segment_name = 'Smart Value Shoppers'\n")
    f.write("                elif income_mean < 40 and spending_mean > 60:\n")
    f.write("                    segment_name = 'Aspiring Trendsetters'\n")
    f.write("                elif income_mean < 40 and spending_mean < 40:\n")
    f.write("                    segment_name = 'Practical Frugal'\n")
    f.write("                elif age_mean < 30 and spending_mean > 60:\n")
    f.write("                    segment_name = 'Young Trend Hunters'\n")
    f.write("                elif age_mean > 50 and income_mean > 60:\n")
    f.write("                    segment_name = 'Established Affluents'\n")
    f.write("                elif age_mean > 50 and spending_mean < 40:\n")
    f.write("                    segment_name = 'Comfort Keepers'\n")
    f.write("                else:\n")
    f.write("                    segment_name = 'Regular Customers'\n")
    f.write("                \n")
    f.write("                segment_details.append({\n")
    f.write("                    'name': segment_name,\n")
    f.write("                    'size': size,\n")
    f.write("                    'pct': percentage,\n")
    f.write("                    'age': age_mean,\n")
    f.write("                    'income': income_mean,\n")
    f.write("                    'spending': spending_mean,\n")
    f.write("                    'female_pct': female_pct,\n")
    f.write("                    'male_pct': male_pct\n")
    f.write("                })\n")
    f.write("            \n")
    f.write("            # Display table\n")
    f.write("            table_data = []\n")
    f.write("            for seg in segment_details:\n")
    f.write("                table_data.append({\n")
    f.write("                    'Segment': seg['name'],\n")
    f.write("                    'Customers': seg['size'],\n")
    f.write("                    'Percentage': str(round(seg['pct'], 1)) + '%',\n")
    f.write("                    'Avg Age': str(round(seg['age'], 0)) + ' yrs',\n")
    f.write("                    'Avg Income': '$' + str(round(seg['income'], 0)) + 'K',\n")
    f.write("                    'Avg Spending': str(round(seg['spending'], 0)) + '/100',\n")
    f.write("                    'Gender': str(round(seg['female_pct'], 0)) + '% F / ' + str(round(seg['male_pct'], 0)) + '% M'\n")
    f.write("                })\n")
    f.write("            \n")
    f.write("            st.dataframe(pd.DataFrame(table_data), use_container_width=True)\n")
    f.write("            \n")
    f.write("            # BAR CHARTS - Age, Income, Spending\n")
    f.write("            st.subheader('Segment Characteristics')\n")
    f.write("            \n")
    f.write("            col1, col2, col3 = st.columns(3)\n")
    f.write("            \n")
    f.write("            with col1:\n")
    f.write("                fig1, ax1 = plt.subplots(figsize=(6, 5))\n")
    f.write("                names = [s['name'][:15] for s in segment_details]\n")
    f.write("                ages = [s['age'] for s in segment_details]\n")
    f.write("                bars1 = ax1.bar(names, ages, color='skyblue', edgecolor='black')\n")
    f.write("                ax1.set_title('Average Age by Segment', fontsize=12, fontweight='bold')\n")
    f.write("                ax1.set_xlabel('Segment', fontsize=10)\n")
    f.write("                ax1.set_ylabel('Age (years)', fontsize=10)\n")
    f.write("                ax1.tick_params(axis='x', rotation=45, labelsize=8)\n")
    f.write("                for bar, age in zip(bars1, ages):\n")
    f.write("                    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1, str(round(age, 0)), ha='center', fontsize=9, fontweight='bold')\n")
    f.write("                plt.tight_layout()\n")
    f.write("                st.pyplot(fig1)\n")
    f.write("            \n")
    f.write("            with col2:\n")
    f.write("                fig2, ax2 = plt.subplots(figsize=(6, 5))\n")
    f.write("                incomes = [s['income'] for s in segment_details]\n")
    f.write("                bars2 = ax2.bar(names, incomes, color='lightgreen', edgecolor='black')\n")
    f.write("                ax2.set_title('Average Income by Segment', fontsize=12, fontweight='bold')\n")
    f.write("                ax2.set_xlabel('Segment', fontsize=10)\n")
    f.write("                ax2.set_ylabel('Income ($K)', fontsize=10)\n")
    f.write("                ax2.tick_params(axis='x', rotation=45, labelsize=8)\n")
    f.write("                for bar, income in zip(bars2, incomes):\n")
    f.write("                    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1, '$' + str(round(income, 0)), ha='center', fontsize=9, fontweight='bold')\n")
    f.write("                plt.tight_layout()\n")
    f.write("                st.pyplot(fig2)\n")
    f.write("            \n")
    f.write("            with col3:\n")
    f.write("                fig3, ax3 = plt.subplots(figsize=(6, 5))\n")
    f.write("                spendings = [s['spending'] for s in segment_details]\n")
    f.write("                bars3 = ax3.bar(names, spendings, color='salmon', edgecolor='black')\n")
    f.write("                ax3.set_title('Average Spending by Segment', fontsize=12, fontweight='bold')\n")
    f.write("                ax3.set_xlabel('Segment', fontsize=10)\n")
    f.write("                ax3.set_ylabel('Spending Score', fontsize=10)\n")
    f.write("                ax3.tick_params(axis='x', rotation=45, labelsize=8)\n")
    f.write("                for bar, spending in zip(bars3, spendings):\n")
    f.write("                    ax3.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1, str(round(spending, 0)), ha='center', fontsize=9, fontweight='bold')\n")
    f.write("                plt.tight_layout()\n")
    f.write("                st.pyplot(fig3)\n")
    f.write("            \n")
    f.write("            # PIE CHART and GENDER CHART\n")
    f.write("            col1, col2 = st.columns(2)\n")
    f.write("            \n")
    f.write("            with col1:\n")
    f.write("                fig4, ax4 = plt.subplots(figsize=(7, 6))\n")
    f.write("                sizes = [s['size'] for s in segment_details]\n")
    f.write("                labels = [s['name'] for s in segment_details]\n")
    f.write("                colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7', '#D4A5A5', '#9B59B6', '#3498DB']\n")
    f.write("                wedges, texts, autotexts = ax4.pie(sizes, labels=labels, autopct='%1.1f%%', colors=colors[:len(sizes)], startangle=90)\n")
    f.write("                ax4.set_title('Customer Segment Distribution', fontsize=14, fontweight='bold')\n")
    f.write("                st.pyplot(fig4)\n")
    f.write("            \n")
    f.write("            with col2:\n")
    f.write("                fig5, ax5 = plt.subplots(figsize=(7, 6))\n")
    f.write("                x = np.arange(len(segment_details))\n")
    f.write("                width = 0.35\n")
    f.write("                female_data = [s['female_pct'] for s in segment_details]\n")
    f.write("                male_data = [s['male_pct'] for s in segment_details]\n")
    f.write("                bars1 = ax5.bar(x, female_data, width, label='Female', color='pink', edgecolor='black')\n")
    f.write("                bars2 = ax5.bar(x, male_data, width, bottom=female_data, label='Male', color='lightblue', edgecolor='black')\n")
    f.write("                ax5.set_xlabel('Segment', fontsize=10)\n")
    f.write("                ax5.set_ylabel('Percentage (%)', fontsize=10)\n")
    f.write("                ax5.set_title('Gender Distribution by Segment', fontsize=12, fontweight='bold')\n")
    f.write("                ax5.set_xticks(x)\n")
    f.write("                ax5.set_xticklabels([s['name'][:10] for s in segment_details], rotation=45, ha='right')\n")
    f.write("                ax5.legend()\n")
    f.write("                for i, (f, m) in enumerate(zip(female_data, male_data)):\n")
    f.write("                    if f > 0:\n")
    f.write("                        ax5.text(i, f/2, str(round(f, 0)) + '%', ha='center', va='center', fontsize=8, fontweight='bold')\n")
    f.write("                    if m > 0:\n")
    f.write("                        ax5.text(i, f + m/2, str(round(m, 0)) + '%', ha='center', va='center', fontsize=8, fontweight='bold')\n")
    f.write("                plt.tight_layout()\n")
    f.write("                st.pyplot(fig5)\n")
    f.write("            \n")
    f.write("            # Quick Summary Cards\n")
    f.write("            st.subheader('Key Insights')\n")
    f.write("            \n")
    f.write("            largest = max(segment_details, key=lambda x: x['size'])\n")
    f.write("            highest_spending = max(segment_details, key=lambda x: x['spending'])\n")
    f.write("            highest_income = max(segment_details, key=lambda x: x['income'])\n")
    f.write("            youngest = min(segment_details, key=lambda x: x['age'])\n")
    f.write("            oldest = max(segment_details, key=lambda x: x['age'])\n")
    f.write("            \n")
    f.write("            col1, col2, col3, col4, col5 = st.columns(5)\n")
    f.write("            col1.info('**Largest Segment**\\n\\n' + largest['name'] + '\\n' + str(largest['size']) + ' customers')\n")
    f.write("            col2.success('**Biggest Spenders**\\n\\n' + highest_spending['name'] + '\\nScore: ' + str(round(highest_spending['spending'], 0)) + '/100')\n")
    f.write("            col3.warning('**Highest Income**\\n\\n' + highest_income['name'] + '\\n$' + str(round(highest_income['income'], 0)) + 'K')\n")
    f.write("            col4.info('**Youngest**\\n\\n' + youngest['name'] + '\\n' + str(round(youngest['age'], 0)) + ' years')\n")
    f.write("            col5.success('**Oldest**\\n\\n' + oldest['name'] + '\\n' + str(round(oldest['age'], 0)) + ' years')\n")
    f.write("            \n")
    f.write("            # Download button\n")
    f.write("            st.subheader('Export Data')\n")
    f.write("            csv = st.session_state.kmeans_df.to_csv(index=False).encode('utf-8')\n")
    f.write("            st.download_button('Download Segmentation Results (CSV)', csv, 'segmentation_results.csv')\n")
    f.write("        else:\n")
    f.write("            st.warning('Please run K-Means clustering first')\n")
    f.write("            st.info('Go to K-Means Clustering page and click Run K-Means')\n")
    f.write("\n")
    f.write("else:\n")
    f.write("    st.info('Please upload a CSV file to begin')\n")
    f.write("    \n")
    f.write("    st.subheader('Expected CSV Format')\n")
    f.write("    example = pd.DataFrame({\n")
    f.write("        'CustomerID': [1, 2, 3, 4, 5],\n")
    f.write("        'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],\n")
    f.write("        'Age': [25, 35, 42, 28, 50],\n")
    f.write("        'Annual Income (k$)': [50, 75, 100, 60, 80],\n")
    f.write("        'Spending Score (1-100)': [60, 75, 85, 70, 65]\n")
    f.write("    })\n")
    f.write("    st.dataframe(example)\n")
    f.write("    \n")
    f.write("    st.subheader('How to Use')\n")
    f.write("    st.markdown('1. Upload your customer CSV file')\n")
    f.write("    st.markdown('2. Select analysis type from dropdown menu')\n")
    f.write("    st.markdown('3. Run clustering algorithm')\n")
    f.write("    st.markdown('4. View customer segments with meaningful names')\n")
    f.write("    st.markdown('5. Download results for your marketing team')\n")

print("Streamlit app created successfully with bar charts!")
