# Create streamlit_app.py - FINAL WORKING VERSION
import os

# Delete old file
if os.path.exists('streamlit_app.py'):
    os.remove('streamlit_app.py')

# Create file line by line - NO SYNTAX ERRORS
with open('streamlit_app.py', 'w', encoding='utf-8') as f:
    f.write("import streamlit as st\n")
    f.write("import pandas as pd\n")
    f.write("import numpy as np\n")
    f.write("import matplotlib.pyplot as plt\n")
    f.write("import seaborn as sns\n")
    f.write("from sklearn.preprocessing import StandardScaler, LabelEncoder\n")
    f.write("from sklearn.cluster import KMeans, DBSCAN\n")
    f.write("from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score\n")
    f.write("from sklearn.decomposition import PCA\n")
    f.write("\n")
    f.write("st.set_page_config(page_title='Customer Segmentation', layout='wide')\n")
    f.write("st.title('Customer Segmentation Dashboard')\n")
    f.write("\n")
    f.write("st.sidebar.header('Upload & Settings')\n")
    f.write("uploaded_file = st.sidebar.file_uploader('Upload CSV Dataset', type=['csv'])\n")
    f.write("\n")
    f.write("st.sidebar.subheader('Navigation')\n")
    f.write("page = st.sidebar.selectbox('Choose Analysis Type', ['K-Means Clustering', 'DBSCAN Clustering', 'Method Comparison', 'Customer Profiling'])\n")
    f.write("\n")
    f.write("if uploaded_file:\n")
    f.write("    df = pd.read_csv(uploaded_file)\n")
    f.write("    st.subheader('Dataset Preview')\n")
    f.write("    st.dataframe(df.head())\n")
    f.write("    \n")
    f.write("    df_clean = df.copy()\n")
    f.write("    if 'Annual Income (k$)' in df_clean.columns:\n")
    f.write("        df_clean.rename(columns={'Annual Income (k$)': 'Annual_Income'}, inplace=True)\n")
    f.write("    if 'Spending Score (1-100)' in df_clean.columns:\n")
    f.write("        df_clean.rename(columns={'Spending Score (1-100)': 'Spending_Score'}, inplace=True)\n")
    f.write("    \n")
    f.write("    if 'Gender' in df_clean.columns:\n")
    f.write("        le = LabelEncoder()\n")
    f.write("        df_clean['Gender_Encoded'] = le.fit_transform(df_clean['Gender'])\n")
    f.write("    else:\n")
    f.write("        df_clean['Gender_Encoded'] = 0\n")
    f.write("    \n")
    f.write("    features = ['Age', 'Annual_Income', 'Spending_Score', 'Gender_Encoded']\n")
    f.write("    X = df_clean[features].copy()\n")
    f.write("    scaler = StandardScaler()\n")
    f.write("    X_scaled = scaler.fit_transform(X)\n")
    f.write("    \n")
    f.write("    if 'kmeans_ran' not in st.session_state:\n")
    f.write("        st.session_state.kmeans_ran = False\n")
    f.write("    if 'dbscan_ran' not in st.session_state:\n")
    f.write("        st.session_state.dbscan_ran = False\n")
    f.write("    if 'kmeans_labels' not in st.session_state:\n")
    f.write("        st.session_state.kmeans_labels = None\n")
    f.write("    if 'kmeans_k' not in st.session_state:\n")
    f.write("        st.session_state.kmeans_k = None\n")
    f.write("    if 'kmeans_sil' not in st.session_state:\n")
    f.write("        st.session_state.kmeans_sil = None\n")
    f.write("    if 'kmeans_cal' not in st.session_state:\n")
    f.write("        st.session_state.kmeans_cal = None\n")
    f.write("    if 'kmeans_dav' not in st.session_state:\n")
    f.write("        st.session_state.kmeans_dav = None\n")
    f.write("    if 'dbscan_labels' not in st.session_state:\n")
    f.write("        st.session_state.dbscan_labels = None\n")
    f.write("    if 'dbscan_clusters' not in st.session_state:\n")
    f.write("        st.session_state.dbscan_clusters = None\n")
    f.write("    if 'dbscan_noise' not in st.session_state:\n")
    f.write("        st.session_state.dbscan_noise = None\n")
    f.write("    if 'dbscan_sil' not in st.session_state:\n")
    f.write("        st.session_state.dbscan_sil = None\n")
    f.write("    if 'kmeans_df' not in st.session_state:\n")
    f.write("        st.session_state.kmeans_df = None\n")
    f.write("    \n")
    f.write("    # K-MEANS CLUSTERING\n")
    f.write("    if page == 'K-Means Clustering':\n")
    f.write("        st.header('K-Means Clustering')\n")
    f.write("        col1, col2 = st.columns([1, 2])\n")
    f.write("        with col1:\n")
    f.write("            k_value = st.slider('Number of Clusters (k)', 2, 10, 5)\n")
    f.write("            if st.button('Run K-Means', type='primary'):\n")
    f.write("                with st.spinner('Running K-Means...'):\n")
    f.write("                    kmeans = KMeans(n_clusters=k_value, random_state=42, n_init=10)\n")
    f.write("                    labels = kmeans.fit_predict(X_scaled)\n")
    f.write("                    df_clean['Cluster'] = labels\n")
    f.write("                    sil_score = silhouette_score(X_scaled, labels)\n")
    f.write("                    cal_score = calinski_harabasz_score(X_scaled, labels)\n")
    f.write("                    dav_score = davies_bouldin_score(X_scaled, labels)\n")
    f.write("                    st.session_state.kmeans_ran = True\n")
    f.write("                    st.session_state.kmeans_labels = labels\n")
    f.write("                    st.session_state.kmeans_k = k_value\n")
    f.write("                    st.session_state.kmeans_sil = sil_score\n")
    f.write("                    st.session_state.kmeans_cal = cal_score\n")
   .write("                    st.session_state.kmeans_dav = dav_score\n")
    f.write("                    st.session_state.kmeans_df = df_clean.copy()\n")
    f.write("                    st.success('Done! Silhouette Score: ' + str(round(sil_score, 4)))\n")
    f.write("        with col2:\n")
    f.write("            if st.session_state.kmeans_ran:\n")
    f.write("                m1, m2, m3 = st.columns(3)\n")
    f.write("                m1.metric('Silhouette Score', str(round(st.session_state.kmeans_sil, 4)))\n")
    f.write("                m2.metric('Calinski-Harabasz', str(round(st.session_state.kmeans_cal, 0)))\n")
    f.write("                m3.metric('Davies-Bouldin', str(round(st.session_state.kmeans_dav, 4)))\n")
    f.write("        if st.session_state.kmeans_ran:\n")
    f.write("            st.subheader('Clustering Results')\n")
    f.write("            pca = PCA(n_components=2)\n")
    f.write("            X_pca = pca.fit_transform(X_scaled)\n")
    f.write("            fig, ax = plt.subplots(figsize=(10, 6))\n")
    f.write("            scatter = ax.scatter(X_pca[:, 0], X_pca[:, 1], c=st.session_state.kmeans_labels, cmap='viridis', s=100, alpha=0.6)\n")
    f.write("            plt.colorbar(scatter)\n")
    f.write("            ax.set_xlabel('First Principal Component')\n")
    f.write("            ax.set_ylabel('Second Principal Component')\n")
    f.write("            ax.set_title('K-Means Clustering Results')\n")
    f.write("            st.pyplot(fig)\n")
    f.write("            st.subheader('Cluster Sizes')\n")
    f.write("            cluster_sizes = pd.Series(st.session_state.kmeans_labels).value_counts().sort_index()\n")
    f.write("            st.bar_chart(cluster_sizes)\n")
    f.write("            st.subheader('Segment Summary - What Each Cluster Means')\n")
    f.write("            summary_data = []\n")
    f.write("            for cluster in range(st.session_state.kmeans_k):\n")
    f.write("                cluster_data = st.session_state.kmeans_df[st.session_state.kmeans_df['Cluster'] == cluster]\n")
    f.write("                size = len(cluster_data)\n")
    f.write("                pct = (size / len(st.session_state.kmeans_df)) * 100\n")
    f.write("                avg_age = cluster_data['Age'].mean()\n")
    f.write("                avg_income = cluster_data['Annual_Income'].mean()\n")
    f.write("                avg_spending = cluster_data['Spending_Score'].mean()\n")
    f.write("                if avg_income > 70 and avg_spending > 60:\n")
    f.write("                    name = 'VIP Premium Customers'\n")
    f.write("                    meaning = 'High income, high spending - Your best customers'\n")
    f.write("                elif avg_income > 70 and avg_spending < 40:\n")
    f.write("                    name = 'Smart Value Shoppers'\n")
    f.write("                    meaning = 'High income but careful spenders - Focus on value deals'\n")
    f.write("                elif avg_income < 40 and avg_spending > 60:\n")
    f.write("                    name = 'Aspiring Trendsetters'\n")
    f.write("                    meaning = 'Lower income but love spending - Use social media marketing'\n")
    f.write("                elif avg_income < 40 and avg_spending < 40:\n")
    f.write("                    name = 'Practical Frugal'\n")
    f.write("                    meaning = 'Budget conscious - Focus on essential items'\n")
    f.write("                elif avg_age < 30 and avg_spending > 60:\n")
    f.write("                    name = 'Young Trend Hunters'\n")
    f.write("                    meaning = 'Young active spenders - Use influencer marketing'\n")
    f.write("                elif avg_age > 50 and avg_income > 60:\n")
    f.write("                    name = 'Established Affluents'\n")
    f.write("                    meaning = 'Mature stable customers - Focus on quality and service'\n")
    f.write("                elif avg_age > 50 and avg_spending < 40:\n")
    f.write("                    name = 'Comfort Keepers'\n")
    f.write("                    meaning = 'Senior cautious spenders - Use traditional marketing'\n")
    f.write("                else:\n")
    f.write("                    name = 'Regular Customers'\n")
    f.write("                    meaning = 'Balanced customers - Mixed marketing approach'\n")
    f.write("                summary_data.append({\n")
    f.write("                    'Cluster': cluster,\n")
    f.write("                    'Segment Name': name,\n")
    f.write("                    'Size': str(size) + ' (' + str(round(pct,1)) + '%',\n")
    f.write("                    'Avg Age': str(round(avg_age,0)),\n")
    f.write("                    'Avg Income': '$' + str(round(avg_income,0)) + 'K',\n")
    f.write("                    'Avg Spending': str(round(avg_spending,0)),\n")
    f.write("                    'What This Means': meaning\n")
    f.write("                })\n")
    f.write("            st.dataframe(pd.DataFrame(summary_data), use_container_width=True)\n")
    f.write("        else:\n")
    f.write("            st.info('Click Run K-Means button to see results')\n")
    f.write("    \n")
    f.write("    # DBSCAN CLUSTERING\n")
    f.write("    elif page == 'DBSCAN Clustering':\n")
    f.write("        st.header('DBSCAN Clustering')\n")
    f.write("        col1, col2 = st.columns([1, 2])\n")
    f.write("        with col1:\n")
    f.write("            eps_value = st.slider('Epsilon (eps)', 0.1, 2.0, 0.8, 0.05)\n")
    f.write("            min_samples_value = st.slider('Min Samples', 2, 20, 5)\n")
    f.write("            if st.button('Run DBSCAN', type='primary'):\n")
    f.write("                with st.spinner('Running DBSCAN...'):\n")
    f.write("                    dbscan = DBSCAN(eps=eps_value, min_samples=min_samples_value)\n")
    f.write("                    labels = dbscan.fit_predict(X_scaled)\n")
    f.write("                    n_clusters = len(set(labels)) - (1 if -1 in labels else 0)\n")
    f.write("                    n_noise = list(labels).count(-1)\n")
    f.write("                    if n_clusters >= 2:\n")
    f.write("                        mask = labels != -1\n")
    f.write("                        sil_score = silhouette_score(X_scaled[mask], labels[mask])\n")
    f.write("                    else:\n")
    f.write("                        sil_score = -1\n")
    f.write("                    st.session_state.dbscan_ran = True\n")
    f.write("                    st.session_state.dbscan_labels = labels\n")
    f.write("                    st.session_state.dbscan_clusters = n_clusters\n")
    f.write("                    st.session_state.dbscan_noise = n_noise\n")
    f.write("                    st.session_state.dbscan_sil = sil_score\n")
    f.write("                    st.success('Done! Found ' + str(n_clusters) + ' clusters')\n")
    f.write("        with col2:\n")
    f.write("            if st.session_state.dbscan_ran:\n")
    f.write("                m1, m2, m3 = st.columns(3)\n")
    f.write("                m1.metric('Clusters Found', st.session_state.dbscan_clusters)\n")
    f.write("                m2.metric('Noise Points', st.session_state.dbscan_noise)\n")
    f.write("                if st.session_state.dbscan_sil is not None and st.session_state.dbscan_sil > 0:\n")
    f.write("                    m3.metric('Silhouette Score', str(round(st.session_state.dbscan_sil, 4)))\n")
    f.write("                else:\n")
    f.write("                    m3.metric('Silhouette Score', 'N/A')\n")
    f.write("        if st.session_state.dbscan_ran:\n")
    f.write("            st.subheader('Clustering Results')\n")
    f.write("            pca = PCA(n_components=2)\n")
    f.write("            X_pca = pca.fit_transform(X_scaled)\n")
    f.write("            fig, ax = plt.subplots(figsize=(10, 6))\n")
    f.write("            unique_labels = set(st.session_state.dbscan_labels)\n")
    f.write("            for k in unique_labels:\n")
    f.write("                mask = st.session_state.dbscan_labels == k\n")
    f.write("                if k == -1:\n")
    f.write("                    ax.scatter(X_pca[mask, 0], X_pca[mask, 1], c='black', s=50, label='Noise', alpha=0.5)\n")
    f.write("                else:\n")
    f.write("                    ax.scatter(X_pca[mask, 0], X_pca[mask, 1], s=50, alpha=0.6, label='Cluster ' + str(k))\n")
    f.write("            ax.set_xlabel('First Principal Component')\n")
    f.write("            ax.set_ylabel('Second Principal Component')\n")
    f.write("            ax.set_title('DBSCAN Clustering Results')\n")
    f.write("            ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')\n")
    f.write("            st.pyplot(fig)\n")
    f.write("            st.subheader('Cluster Distribution')\n")
    f.write("            cluster_counts = pd.Series(st.session_state.dbscan_labels).value_counts()\n")
    f.write("            st.bar_chart(cluster_counts)\n")
    f.write("        else:\n")
    f.write("            st.info('Click Run DBSCAN button to see results')\n")
    f.write("    \n")
    f.write("    # METHOD COMPARISON\n")
    f.write("    elif page == 'Method Comparison':\n")
    f.write("        st.header('Algorithm Comparison')\n")
    f.write("        if st.session_state.kmeans_ran and st.session_state.dbscan_ran:\n")
    f.write("            comp_data = {\n")
    f.write("                'Algorithm': ['K-Means', 'DBSCAN'],\n")
    f.write("                'Silhouette Score': [str(round(st.session_state.kmeans_sil,4)), str(round(st.session_state.dbscan_sil,4)) if st.session_state.dbscan_sil > 0 else 'N/A'],\n")
    f.write("                'Segments': [st.session_state.kmeans_k, st.session_state.dbscan_clusters],\n")
    f.write("                'Noise Points': ['None', str(st.session_state.dbscan_noise)]\n")
    f.write("            }\n")
    f.write("            st.dataframe(pd.DataFrame(comp_data), use_container_width=True)\n")
    f.write("        else:\n")
    f.write("            st.warning('Please run both K-Means and DBSCAN first')\n")
    f.write("    \n")
    f.write("    # CUSTOMER PROFILING\n")
    f.write("    elif page == 'Customer Profiling':\n")
    f.write("        st.header('Customer Segment Profiles')\n")
    f.write("        if st.session_state.kmeans_ran and st.session_state.kmeans_df is not None:\n")
    f.write("            st.subheader('Segment Overview')\n")
    f.write("            profiles = []\n")
    f.write("            for cluster in range(st.session_state.kmeans_k):\n")
    f.write("                cluster_data = st.session_state.kmeans_df[st.session_state.kmeans_df['Cluster'] == cluster]\n")
    f.write("                size = len(cluster_data)\n")
    f.write("                pct = (size / len(st.session_state.kmeans_df)) * 100\n")
    f.write("                age = cluster_data['Age'].mean()\n")
    f.write("                income = cluster_data['Annual_Income'].mean()\n")
    f.write("                spending = cluster_data['Spending_Score'].mean()\n")
    f.write("                if income > 70 and spending > 60:\n")
    f.write("                    name = 'VIP Premium Customers'\n")
    f.write("                elif income > 70 and spending < 40:\n")
    f.write("                    name = 'Smart Value Shoppers'\n")
    f.write("                elif income < 40 and spending > 60:\n")
    f.write("                    name = 'Aspiring Trendsetters'\n")
    f.write("                elif income < 40 and spending < 40:\n")
    f.write("                    name = 'Practical Frugal'\n")
    f.write("                elif age < 30 and spending > 60:\n")
    f.write("                    name = 'Young Trend Hunters'\n")
    f.write("                elif age > 50 and income > 60:\n")
    f.write("                    name = 'Established Affluents'\n")
    f.write("                elif age > 50 and spending < 40:\n")
    f.write("                    name = 'Comfort Keepers'\n")
    f.write("                else:\n")
    f.write("                    name = 'Regular Customers'\n")
    f.write("                profiles.append({\n")
    f.write("                    'Segment': name,\n")
    f.write("                    'Customers': size,\n")
    f.write("                    '%': str(round(pct,1)) + '%',\n")
    f.write("                    'Avg Age': str(round(age,0)),\n")
    f.write("                    'Avg Income': '$' + str(round(income,0)) + 'K',\n")
    f.write("                    'Avg Spending': str(round(spending,0))\n")
    f.write("                })\n")
    f.write("            st.dataframe(pd.DataFrame(profiles), use_container_width=True)\n")
    f.write("            st.subheader('Export Data')\n")
    f.write("            csv = st.session_state.kmeans_df.to_csv(index=False).encode('utf-8')\n")
    f.write("            st.download_button('Download Results', csv, 'segmentation_results.csv')\n")
    f.write("        else:\n")
    f.write("            st.warning('Please run K-Means first')\n")
    f.write("\n")
    f.write("else:\n")
    f.write("    st.info('Please upload a CSV file to begin')\n")
    f.write("    st.subheader('Expected CSV Format')\n")
    f.write("    example = pd.DataFrame({\n")
    f.write("        'CustomerID': [1,2,3],\n")
    f.write("        'Gender': ['Male','Female','Female'],\n")
    f.write("        'Age': [25,35,42],\n")
    f.write("        'Annual Income (k$)': [50,75,100],\n")
    f.write("        'Spending Score (1-100)': [60,75,85]\n")
    f.write("    })\n")
    f.write("    st.dataframe(example)\n")

print("Streamlit app created successfully!")
